// <auto-generated />
using System;
using Almoxarifado.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Almoxarifado.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529173454_AdicionandoValidacoes")]
    partial class AdicionandoValidacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsumivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catalogos");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MochilaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("MochilaId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Mochila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mochilas");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAlmoxarife")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Equipamento", b =>
                {
                    b.HasOne("Almoxarifado.Domain.Entities.Catalogo", "Catalogo")
                        .WithMany("Equipamentos")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Almoxarifado.Domain.Entities.Mochila", null)
                        .WithMany("Equipamentos")
                        .HasForeignKey("MochilaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Catalogo");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Mochila", b =>
                {
                    b.OwnsOne("Almoxarifado.Domain.ValueObjects.OperacaoTurno", "OperacaoAtual", b1 =>
                        {
                            b1.Property<int>("MochilaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Dupla")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("DuplaAtual");

                            b1.Property<string>("Turno")
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("TurnoAtual");

                            b1.HasKey("MochilaId");

                            b1.ToTable("Mochilas");

                            b1.WithOwner()
                                .HasForeignKey("MochilaId");
                        });

                    b.Navigation("OperacaoAtual");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("Almoxarifado.Domain.Entities.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almoxarifado.Domain.Entities.Catalogo", "Catalogo")
                        .WithMany()
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almoxarifado.Domain.Entities.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agente");

                    b.Navigation("Catalogo");

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Catalogo", b =>
                {
                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("Almoxarifado.Domain.Entities.Mochila", b =>
                {
                    b.Navigation("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
